[package]
name = "r_ray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r_vector = { git = "https://github.com/elapuestojoe/r_vector", branch = "main" }
num = "0.4"